--- 
abstract: ~
author: 
  - Luke Saunders <luke.saunders@gmail.com>
build_requires: 
  Catalyst::Model::DBIC::Schema: 0.2
  Test::More: 0.7
  Test::WWW::Mechanize: 0.2
  Test::WWW::Mechanize::Catalyst: 0.37
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Controller-DBIC-API
no_index: 
  directory: 
    - inc
    - t
requires: 
  CGI::Expand: 2.02
  Catalyst::Action::REST: 0.6
  Catalyst::Runtime: 5.701
  DBIx::Class: 0.08
  perl: 5.6.1
tests: t/rest/*.t t/rpc/*.t
version: 1.001000
