---
abstract: ~
author:
  - 'Luke Saunders <luke.saunders@gmail.com>'
build_requires:
  Catalyst::Model::DBIC::Schema: 0.2
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.7
  Test::WWW::Mechanize: 0.2
  Test::WWW::Mechanize::Catalyst: 0.37
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.88'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Controller-DBIC-API
no_index:
  directory:
    - inc
    - t
requires:
  CGI::Expand: 2.02
  Catalyst::Action::REST: 0.6
  Catalyst::Runtime: 5.701
  DBIx::Class: 0.08
  JSON::Any: 1.19
  Test::Deep: 0.104
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 1.003000
