---
abstract: 'Provides a DBIx::Class web service automagically'
author:
  - 'Nicholas Perez <nperez@cpan.org>'
  - 'Luke Saunders <luke.saunders@gmail.com>'
  - 'Alexander Hartmaier <abraxxa@cpan.org>'
  - 'Florian Ragwitz <rafl@debian.org>'
  - 'Oleg Kostyuk <cub.uanic@gmail.com>'
build_requires:
  Test::Deep: 0.104
  Test::More: 0.88
  Test::WWW::Mechanize::Catalyst: 0.37
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Controller-DBIC-API
no_index:
  directory:
    - t/lib
requires:
  CGI::Expand: 2.02
  Catalyst::Action::Serialize: 0.83
  Catalyst::ActionRole::MatchRequestMethod: 0
  Catalyst::Controller::ActionRole: 0
  Catalyst::Model::DBIC::Schema: 0.20
  Catalyst::Runtime: 5.7010
  DBIx::Class: 0.08103
  Data::DPath::Validator: 0.093411
  JSON: 2.50
  MooseX::Types::Structured: 0.20
  perl: 5.008006
resources:
  repository: git://git.shadowcat.co.uk/catagits/Catalyst-Controller-DBIC-API
version: 2.004002
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Basic/GatherDir'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Basic/PruneCruft'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Basic/ManifestSkip'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Basic/MetaYAML'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::License
      name: '@Basic/License'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Basic/Readme'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Basic/ExtraTests'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Basic/ExecDir'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Basic/ShareDir'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Basic/MakeMaker'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Basic/Manifest'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Basic/TestRelease'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Basic/ConfirmRelease'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Basic/UploadToCPAN'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: PodWeaver
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: PodCoverageTests
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: Test::Portability
      version: 2.0.2
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: Test::DistManifest
      version: 2.0.1
    -
      class: Dist::Zilla::Plugin::Test::Synopsis
      name: Test::Synopsis
      version: 2.0.1
    -
      class: Dist::Zilla::Plugin::Test::UnusedVars
      name: Test::UnusedVars
      version: 2.0.1
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: HasVersionTests
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300002
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300002
